config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  
  # Notes the registrations controller will manage user registrations
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  # nesting the 'profile' resource within the users resource
  resources :users do
    resource :profile
  end
  
  get 'about', to: 'pages#about'
  
  # Creates all CRUD routes for Contacts rather than having to write a line for every permutation, ie get 'contacts/new'
  # Also offers a bunch of routes that can be seen using $ rails routes
  resources :contacts, only: :create
  
  # Creates a custom URL for a /contact-us page rather than having them goto /contacts/new
  # This will make the application read from the 'contacts' controller and run the 'new' action (function)
  # Adding the 'as:' allows us to keep the default path name for creating a new contact
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
    
  has_attached_file :avatar, 
                    styles: { medium: "300x300>", thumb: "100x100>" }, 
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # Lock down all user pages if not logged-in  
  before_action :authenticate_user!
  
  # Define a method to ensure users can only edit their own profiles
  before_action :only_current_user
  
  # GET to /users/:user_id/profile/new
  def new
    @profile = Profile.new
  end
  
  # POST to /users/:user_id/profile
  def create
    # Grab the user object from the DB using the URL params
    # User.find(1) will return the object that is stored at that location
    @user = User.find( params[ :user_id ] )
     
    # Associate the @profile variable with the user that is logged in per params
    # build_profile is a new method that is used when we have associated data
    # "build_profile" is similar to "Profile.new", but build_profile allows us 
    # to associate the Profile to that user_id when storing the data (1:1 relationship)
    # We would use @user.profile.build if it were a 1:many relationship
    @profile = @user.build_profile( profile_params )
    
    if @profile.save
      # Generate a flash message to let the user know the save was successful
      flash[:success] = "Profile Updated!"
      redirect_to user_path(id: params[:user_id])
    else
      # Re-render the form to allow the user to re-submit
      # Render does NOT make a new HTTP request, unlike "redirect_to"
      render action: :new
    end
  end
  
  # GET to /users/:user_id/profile/edit
  def edit
    # Set the user based on the user_id parameter
    @user = User.find(params[:user_id])
    # Define the form data using @profile by assigning it the value of the user's profile
    @profile = @user.profile
  end
  
  # PATCH to users/:user_id/profile
  # We use "update" because that's what the rails routes show us: 'users#update'
  def update
    # Retrieve user from db
    @user = User.find(params[:user_id])
    # Retrieve that user's profile
    @profile = @user.profile
    
    # Mass assign edited profile attributes from whitelisting below
    if @profile.update_attributes(profile_params)
      flash[:success] = "Profile has been updated!"
      redirect_to user_path(id: params[:user_id])
    else
      render action: :edit
    end
    
  end
  
  private
    # Creating a private method to ensure that all of the required parameters are sent when hitting submit
    # This private method can only be used inside of this file
    def profile_params
      # Whitelisting all of the parameters for security
      params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description)
    end
    
    #Define a method to check that the user is only attempting to edit their own profile page
    def only_current_user
      # Identify the currently signed-in user
      @user = User.find(params[:user_id])
      
      # Redirect the user to the homepage unless they are the found user
      redirect_to(root_url) unless @user == current_user
    end
end

app/views/profiles/_form.html.erb
<!--We have to specify the URL because this is a nested form for a specific user-->
<!--On Inspect, the form gets 'action="/users/:user_id/profile"' because of the URL path we set-->
<!--We need "multipart" because we are inputting an image-->
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
    
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :job_title %>
    <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {prompt:"**Please select an option**"}, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  
  <%= f.submit "Update my profile", class: 'btn btn-info btn-lg btn-block' %>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Edit your profile</h1>
      <p class="text-center">Be a part of the DevMatch Community and update your profile!</p>
      <div class="well">
        <!--Pull in any HTML in the '_form.html.erb' file in the same folder-->
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Create your profile</h1>
      <p class="text-center">Be a part of the DevMatch Community and fill out your profile!</p>
      <div class="well">
        <!--Pull in any HTML in the '_form.html.erb' file in the same folder-->
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>