config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  
  # Notes the registrations controller will manage user registrations
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  # nesting the 'profile' resource within the users resource
  resources :users do
    resource :profile
  end
  
  get 'about', to: 'pages#about'
  
  # Creates all CRUD routes for Contacts rather than having to write a line for every permutation, ie get 'contacts/new'
  # Also offers a bunch of routes that can be seen using $ rails routes
  resources :contacts, only: :create
  
  # Creates a custom URL for a /contact-us page rather than having them goto /contacts/new
  # This will make the application read from the 'contacts' controller and run the 'new' action (function)
  # Adding the 'as:' allows us to keep the default path name for creating a new contact
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/views/pages/about.html.erb
<div class="container text-center">
  <div class="row">
    <h1>About Us</h1>
    <p>We are DevMatch. Our company focuses on creating an exclusive community 
    for developers, entrepreneurs, and investors to meet.</p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
    <h1>Welcome to DevMatch!</h1>
    <h3>A membership site where Entrepreneurs can meet Developers</h3>
</div>

<div class="container home-signup-links">
    <div class="row">
      
      <% if user_signed_in? %>
        <div class="col-md-6">
          <div class="well">
            <h2 class="text-center">Your Profile</h2>
            
            <% if current_user.profile %>
              <%= link_to "Edit your Profile", edit_user_profile_path(user_id: current_user.id), class: "btn btn-default btn-lg btn-block" %>
              <%= link_to "View your Profile", user_path(id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
            
            <% else %>
              <p>Create your profile so you can share your information with the community</p>
              <%= link_to "Create your profile", new_user_profile_path(user_id: current_user.id), class: "btn btn-default btn-lg btn-block" %>
            <% end %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="well">
            <h2 class="text-center">The Community</h2>
            <p>Visit the community to meet other developers, entrepreneurs. and investors!</p>
            <%= link_to "Visit the community", users_path, class: 'btn btn-default btn-lg btn-block' %>
          </div>
        </div>
      
      <% else %>
        <div class="col-md-6">
            <div class="well">
                <h2 class="text-center">Basic Membership</h2>
                <br>
                <h4 class="text-center">Sign up for free and get basic access to the community</h4>
                <br><br>
                <!--(plan: xxxxx) creates a query parameter to be sent with that link to be used by the next page-->
                <%= link_to "Sign up with Basic plan", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
            </div>
        </div>
        
        <div class="col-md-6">
            <div class="well">
                <h2 class="text-center">Pro Membership</h2>
                <br>
                <h4 class="text-center">Sign up for the Pro account for $10/month and get access to the community and contact information!</h4>
                <br>
                <!--(plan: xxxxx) creates a query parameter to be sent with that link to be used by the next page-->
                <%= link_to "Sign up with Pro plan", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg  btn-block' %>
            </div>
        </div>
      <% end %>
    </div>
</div>