config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  
  # Notes the registrations controller will manage user registrations
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  # nesting the 'profile' resource within the users resource
  resources :users do
    resource :profile
  end
  
  get 'about', to: 'pages#about'
  
  # Creates all CRUD routes for Contacts rather than having to write a line for every permutation, ie get 'contacts/new'
  # Also offers a bunch of routes that can be seen using $ rails routes
  resources :contacts, only: :create
  
  # Creates a custom URL for a /contact-us page rather than having them goto /contacts/new
  # This will make the application read from the 'contacts' controller and run the 'new' action (function)
  # Adding the 'as:' allows us to keep the default path name for creating a new contact
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saasapp</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Montserrat:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://js.stripe.com/v2/', type: 'text/javascript' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  </head>

  <body>
    
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
              <i class ="fa fa-group"></i>
              DevMatch
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
            <ul class="nav navbar-nav navbar-right">  
              <li><%= link_to "About", about_path %></li>
              <!--Find the route below using $ rails routes, where the "new_contact" is the GET method for the /contacts/new page-->
              <li><%= link_to "Contact Us", new_contact_path %></li>
              <!--if statement to handle conditional logout button-->
              <!--'method' required for a 'DELETE' on a link - normally a 'GET'-->
              <% if user_signed_in? %>
                <li><%= link_to "Community", users_path %></li>
                <li><%= link_to "MyAccount", edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'user-btn' %></li>
              <% else %>
                <li><%= link_to "Log In", user_session_path, class: 'user-btn' %></li>
              <% end %>
            </ul>
            </div>  
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    
    <!--Showing error messages here to guarantee we're showing errors no matter where we re-direct users to-->
    <!--"Flash" is to show the notices as outlined in the ContactsController-->
    <!--There is no "=" after the ruby tag since this should not be output until there is a value in the "type" and "message" values-->
    <!--(Entering a "=" will cause the page to show a blank hash '{}' and to double the alerts rather than only showing once and applying our classes below-->
    <!--'Type' is akin to 'key', and 'msg' is akin to the error 'value'-->
    <div class="container flash-container">
      <% flash.each do |type, msgs| %>
        <!--'content_tag' allows us to have rails insert an HTML tag (div) into our code-->
        <!--Using string interpolation, you can inject the 'type' into the class to show which class to use based on success or danger-->
        <%= content_tag :div, msgs, class: "alert alert-#{type}" %>
      <% end %>
    </div>
    
    <%= yield %>
    
  </body>
</html>